### ISSUE TITLE
Migrated Funds Not Available

### ISSUE THREAD

**Issue by darrenjschumaker** [cardano-foundation/incentivized-testnet-stakepool-registry#442]
I have migrated funds from my Byron to my Shelley wallet.  I have confirmed their status via

 cardano-wallet wallet get $ShelleyID
and 
cardano-wallet transaction list $ShelleyID

However, when using jcli to get account 
.\jcli.exe rest v0 account get $Addr -h http://127.0.0.1:3101/api
the returned values are 0
counter: 0
delegation:
  pools: []
last_rewards:
  epoch: 0
  reward: 0
value: 0

**Comment by KtorZ** [comment]
Hey :) 
When migrating your Byron wallet to your Shelley wallet, you're still trading UTxOs for UTxOs. They are simply "moved" from a wallet to another. 
Now, once this is done, you still have to send some funds to your owner account in order to pay for the pool registration. This is detailed in [How to Register Your Stake Pool on Chain - Step 3](https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/wiki/How-to-Register-Your-Stake-Pool-on-Chain#step-3-fund-your-account). 

In particular, if you are comfortable with the command-line, you might look into option B and jump directly to:

```
$ cardano-wallet transaction create 2d4cc31a4b3116ab86bfe529d30d9c362acd0b44 \
  --payment $PLEDGE_AMOUNT@$(cat owner.addr)
```

Where `$PLEDGE_AMOUNT` is simply the initial amount you want to send to the account. This needs to be (obviously) smaller than your wallet balance and sufficient to pay for the registration fee. The remaining will be automatically delegated to your pool.

**Comment by darrenjschumaker** [comment]
I'm confused Matthias.  How can I send the funds if the balance shows 0?

________________________________

**Comment by darrenjschumaker** [comment]
This was my BYRON_ID=55387a27e1c97a941e3d9ceb5eaa3a44d425824b

This is my Shelley_ID:1c280e292501f187380c1eb38eee844b2d1efa6e

The account address I have that corresponds to my Shelley wallet is addr1s44xwzznjgw0yc44p4s4tlzd4crqafuy4nc999qutlfsqar95gl3kw75mcx

________________________________

**Comment by darrenjschumaker** [comment]
cardano-wallet wallet get 1c280e292501f187380c1eb38eee844b2d1efa6e
returns
{
    "passphrase": {
        "last_updated_at": "2019-12-13T22:46:04.9922966Z"
    },
    "address_pool_gap": 20,
    "state": {
        "status": "ready"
    },
    "balance": {
        "reward": {
            "quantity": 0,
            "unit": "lovelace"
        },
        "total": {
            "quantity": 468574136270,
            "unit": "lovelace"
        },
        "available": {
            "quantity": 468574136270,
            "unit": "lovelace"
        }
    },
    "name": "Darren",
    "delegation": {
        "status": "not_delegating"
    },
    "id": "1c280e292501f187380c1eb38eee844b2d1efa6e",
    "tip": {
        "height": {
            "quantity": 970,
            "unit": "block"
        },
        "epoch_number": 0,
        "slot_number": 10091
    }
}

________________________________

**Comment by KtorZ** [comment]
Hey, it can be a little confusing indeed. Jörmungandr actually support chimeric ledger. Said differently, you may use both UTxO and mutable accounts, and the usage depends on what you do. Rewards are collected in an account and, an account is also necessary to register a stake pool.

However, `cardano-wallet` (and by extension Daedalus) helps you manage your UTxOs in your wallet. Hence, your account balance might be empty, but your UTxO balance is far from empty :)

```json
       ... 
      "available": {
            "quantity": 468574136270,
            "unit": "lovelace"
        }
       ... 
```

Therefore, you need a to make a transaction to transfer some of your UTxO into your owner account. Unfortunately, you can't yet use your UTxO to pay for your pool registration directly; this should become available in the MainNet.

**Comment by AWCrypt** [comment]
Hi, I'm in the same situation.

**Comment by KtorZ** [comment]
Hi @AWCrypt, this is **not** what I am saying no.

In order to pay for a registration certificate you need to send funds to the owner account associate with the certificate. You can do so by using cardano-wallet to transfer funds from your wallet to your owner account.
The steps to do so are details in the Step 3 of the step-by-step guide I linked earlier.

**Comment by darrenjschumaker** [comment]
Thank you Matthias.  I was able to get my accounts migrated and properly funded.  My stake pool is registered and delegated to now.

________________________________
