### ISSUE TITLE
Delete ALOHA pool --- need to recreate

### ISSUE THREAD

**Issue by cardanohawaiipool** [cardano-foundation/incentivized-testnet-stakepool-registry#519]
Please delete the ALOHA pool that I made and has been merged. The public key is incorrect to match with my pool on the ITN. I will resubmit a new pull request with new json and sig files once it's gone. Thanks.

**Comment by KtorZ** [comment]
@cardanohawaiipool could you point to your original PR please?

Also, know that removing a pool from the registry is an ad-hoc process that we would rather avoid. Rationale and a work-around are detailed here: https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/issues/394#issuecomment-565431466

I'd suggest you to go through the steps described in this comment and void your previous registration in order to submit a new one.

**Comment by KtorZ** [comment]
cc @admin-cf

**Comment by cardanohawaiipool** [comment]
https://github.com/cardano-foundation/incentivized-testnet-stakepool-registry/pull/199

**Comment by KtorZ** [comment]
See also: #641
