### ISSUE TITLE
help

### ISSUE THREAD

**Issue by z6586** [cardano-foundation/incentivized-testnet-stakepool-registry#731]
jcli rest v0 account get addr1s50wkg689ksnvxrur4p67ncv6tq453axd2uvexv4jyeufetptr5gz39u00j -h  http://127.0.0.1:3100/api
failed to make a REST request
  |-> node rejected request because of invalid parameters
  |-> http://127.0.0.1:3100/api/v0/account/1eeb23472da136187c1d43af4f0cd2c15a47a66ab8cc99959133c4e56158e881: Client Error: 404 Not Found

**Comment by KtorZ** [comment]
Hi, if you are encountering issues with `jcli` or `jormungandr`, I'd suggest to report this issue directly to their official repository: https://github.com/input-output-hk/jormungandr/issues

However, keep in mind that in order to help you the best, people will need to understand:

- What is your problem (what are you trying to achieve?)
- What would you expect 
- What issue your are facing
- Versions of softwares you use
- Some extra details about your operating system 
- An indication of your proficiency and expertise of the topic

Cheers.
