### ISSUE TITLE
Lost my funds

### ISSUE THREAD

**Issue by wstrik** [cardano-foundation/incentivized-testnet-stakepool-registry#859]
I keep having issues with sending my stake pool credentials, related to issue #592 But I keep trying.
Now I'm checking the funds in my wallet and there gone. I have 1 transfer which sends some funds to my stake pool. But now there all gone:
[https://shelleyexplorer.cardano.org/en/address/addr1s38t9jn0ek9e37xem9mk4y3czswemlkgq4dff52xjhd04zvdeah2x0uj2e0pxu0y3tych3g58qal0asmnqwfgu2443xcdkfv7q7qxdca9mqh2a/](https://shelleyexplorer.cardano.org/en/address/addr1s38t9jn0ek9e37xem9mk4y3czswemlkgq4dff52xjhd04zvdeah2x0uj2e0pxu0y3tych3g58qal0asmnqwfgu2443xcdkfv7q7qxdca9mqh2a/)

![Screenshot 2019-12-19 at 13 49 27](https://user-images.githubusercontent.com/767227/71175294-7fd71780-2267-11ea-966d-216c27ecdad3.png)

**Comment by KtorZ** [comment]
Hi @wstrik , we've ran into various challenging issues due to the heavy activity on the network. In some cases, the wallet end up removing local checkpoints that should not be removed, leaving the reported balance incorrect (while still keeping a correct transaction history however). As a workaround, you may delete your wallet and restore it again. Your funds aren't gone, they simply are not reported correctly. 

We are still working on a fix that doesn't impact users and wallet performances too much.
