### ISSUE TITLE
Missing Listing in Daedalus Wallet

### ISSUE THREAD

**Issue by Sandboxgamer** [cardano-foundation/incentivized-testnet-stakepool-registry#861]
What can I do if  I still miss the listing of a node in the daedaluswallet after a successfull merging?

**Comment by KtorZ** [comment]
Hi, we've found an issue on the wallet backend partly due to network instability in this first week. It's relatively invisible to end-users, but it prevents the stake pools list from being updated in a timely manner. This has been fixed and will be part of the release early next week. 

At the moment, you may work-around this by removing your local data (`rm ~/.local/share/Daedalus/itn_rewards_v1/wallets/stake-pools.sqlite`) and restarting Daedalus. Sorry for the inconvenience!
